name: couleur
description: "Ephemeral chat"
publish_to: 'none'
version: 1.2.1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.7.3
  intl: any
  ndk: ^0.10.0-dev.5
  ndk_flutter: ^0.10.0-dev.6
  ndk_drift: ^0.1.1-dev.17
  shared_preferences: ^2.5.5
  system_theme: ^3.3.0
  url_launcher: ^6.3.2
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
